In [8]:
import numpy as np

In [11]:
A = np.array([[1, -1],
             [ 2, -2]])

# Alternative for transposing A and creating A_T automatically
A_T = A.T

AA_T = np.matmul(A, A_T)

AA_T


array([[2, 4],
       [4, 8]])

In [4]:
A = np.array([[1, -1],
             [ 2, -2]])

A_T = np.array([[1, 2],
               [-1, -2]])

AA_T = np.matmul(A, A_T)

AA_T


array([[2, 4],
       [4, 8]])

In [5]:
A = np.array([[1, -1],
             [ 2, -2]])

A_T = np.array([[1, 2],
               [-1, -2]])

AA_T = np.dot(A, A_T)

AA_T


array([[2, 4],
       [4, 8]])

In [6]:
A = np.array([[1, -1],
             [ 2, -2]])

A_T = np.array([[1, 2],
               [-1, -2]])

AA_T = A @ A_T

AA_T


array([[2, 4],
       [4, 8]])